name: build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean previous execution
      run: rm -rf build; rm -rf SFML
    - name: Create build directory
      run: mkdir build
    - name: Aptitude update
      run: sudo apt-get update
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Install G++ and build-essential
      run: sudo apt-get install -y build-essential g++
    - name: Install git
      run: sudo apt-get install -y git
    - name: Install ALSA
      run: sudo apt-get install -y libasound2 alsa-utils alsa-oss libasound2-dev
    - name: Install SFML dependencies
      run: sudo apt install libfreetype6-dev libxrandr-dev libudev-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev libgl1-mesa-dev
    - name: Retrieve SFML 2.5.1
      run: "git clone --branch 2.5.1 --depth 1 http://github.com/SFML/SFML.git"
    - name: Compile and install SFML
      run: cd SFML; cmake .; make -j8; sudo make install
    - name: Compile ObENgine
      run: cd build; cmake -DBUILD_TESTS=ON ..; make -j8
    - name: Run tests
      run: ./build/tests/ObEngineTests


  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: mkdir build
    - name: Download pre-built SFML
      run: Invoke-WebRequest -Uri "https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip" -OutFile SFML-2.5.1.zip
      shell: pwsh
    - name: Extract SFML
      run: Expand-Archive -LiteralPath SFML-2.5.1.zip -DestinationPath build
      shell: pwsh
    - name: Display tree
      shell: pwsh
    - name: Run CMake on ObEngine
      run: cd build; cmake -G "Visual Studio 16 2019" -A x64 -DSFML_DIR=./SFML-2.5.1/lib/cmake/SFML -DBUILD_TESTS=ON ..
    - name: Compile ObEngine
      run: cmake --build build